In [ ]:
#Identification-of-Erythemato-Squamous-Disease

"""A kind of skin illness is called erythemato-squamous disease (ESD). It often results in skin redness and may also result in skin loss. The erythemato-squamous diseases (ESDs) are another widespread skin condition. Psoriasis, seboreic dermatitis, lichen planus, pityriasis rosea, chronic dermatitis, and pityriasis rubra pilaris are among the six distinct classifications. With very few exceptions, they all exhibit erythema and scaling as clinical characteristics. Dermatologists acknowledge that diagnosing ESD is a difficult problem.

Erythemato-squamous disease (ESD) is a skin condition, as is already well known. These illnesses have a complex etiology, delayed progression, and incomplete healing despite therapy. Genetic factors contribute to the genesis of these illnesses. Erythemato-squamous skin conditions have a detrimental impact on a person's mental, social, and quality of life. They also put a strain on the family's psychological well-being and social mental health. These illnesses have substantial treatment costs and negative economic effects due to the expensive treatments that must be imported. We recognize these disorders for this reason.

Analysis of clinical data enables a deeper comprehension of disease-causing processes. Additionally, it enables us to comprehend how risk factors affect the course of a disease. The amount of data available to clinicians has increased significantly. The discipline of medicine benefits from machine learning. Medical experts may apply machine learning in healthcare to create better diagnostic tools for examining medical pictures. That is why we employ a machine learning strategy. There aren't many examples of deep learning being used to diagnose ESD. In the dermatological dataset, machine learning is shown to perform well. Utilizing datasets, the technique trains itself using machine learning technologies."""

"A kind of skin illness is called erythemato-squamous disease (ESD). It often results in skin redness and may also result in skin loss. The erythemato-squamous diseases (ESDs) are another widespread skin condition. Psoriasis, seboreic dermatitis, lichen planus, pityriasis rosea, chronic dermatitis, and pityriasis rubra pilaris are among the six distinct classifications. With very few exceptions, they all exhibit erythema and scaling as clinical characteristics. Dermatologists acknowledge that diagnosing ESD is a difficult problem.\n\nErythemato-squamous disease (ESD) is a skin condition, as is already well known. These illnesses have a complex etiology, delayed progression, and incomplete healing despite therapy. Genetic factors contribute to the genesis of these illnesses. Erythemato-squamous skin conditions have a detrimental impact on a person's mental, social, and quality of life. They also put a strain on the family's psychological well-being and social mental health. These illnes

In [29]:
#dataset
#import pandas

import pandas as pd
data=pd.read_csv('dermatologydata.csv')
data

Patient ID  Erythema  scaling  definite borders  itching  \
0           P1         2        2                 0        3   
1           P2         3        3                 3        2   
2           P3         2        1                 2        3   
3           P4         2        2                 2        0   
4           P5         2        3                 2        2   
..         ...       ...      ...               ...      ...   
361       P362         2        1                 1        0   
362       P363         3        2                 1        0   
363       P364         3        2                 2        2   
364       P365         2        1                 3        1   
365       P366         3        2                 2        0   

     koebner phenomenon  polygonal papules  follicular papules  \
0                     0                  0                   0   
1                     1                  0                   0   
2                     1                  3                   0   
3                     0                  0                   0   
4                     2                  2                   0   
..                  ...                ...                 ...   
361                   1                  0                   0   
362                   1                  0                   0   
363                   3                  2                   0   
364                   2                  3                   0   
365                   0                  0                   0   

     oral mucosal involvement  knee and elbow involvement  ...  \
0                           0                           1  ...   
1                           0                           1  ...   
2                           3                           0  ...   
3                           0                           3  ...   
4                           2                           0  ...   
..                        ...                         ...  ...   
361                         0                           0  ...   
362                         0                           0  ...   
363                         2                           0  ...   
364                         2                           0  ...   
365                         0                           3  ...   

     disappearance of the granular layer  \
0                                      0   
1                                      0   
2                                      0   
3                                      3   
4                                      2   
..                                   ...   
361                                    0   
362                                    1   
363                                    0   
364                                    0   
365                                    2   

     vacuolisation and damage of basal layer  spongiosis  \
0                                          0           3   
1                                          0           0   
2                                          2           3   
3                                          0           0   
4                                          3           2   
..                                       ...         ...   
361                                        0           1   
362                                        0           1   
363                                        3           0   
364                                        2           0   
365                                        0           0   

     saw-tooth appearance of retes  follicular horn plug  \
0                                0                     0   
1                                0                     0   
2                                2                     0   
3                                0                     0   
4                                3                     0   
..                             ...     

In [30]:
#data type
data.dtypes


Patient ID                                  object
Erythema                                     int64
scaling                                      int64
definite borders                             int64
itching                                      int64
koebner phenomenon                           int64
polygonal papules                            int64
follicular papules                           int64
oral mucosal involvement                     int64
knee and elbow involvement                   int64
scalp involvement                            int64
family history, (0 or 1)                     int64
melanin incontinence                         int64
eosinophils in the infiltrate                int64
PNL infiltrate                               int64
fibrosis of the papillary dermis             int64
exocytosis                                   int64
acanthosis                                   int64
hyperkeratosis                               int64
parakeratosis                  

In [31]:
#finding_missing_value
data.isnull().sum()


Patient ID                                  0
Erythema                                    0
scaling                                     0
definite borders                            0
itching                                     0
koebner phenomenon                          0
polygonal papules                           0
follicular papules                          0
oral mucosal involvement                    0
knee and elbow involvement                  0
scalp involvement                           0
family history, (0 or 1)                    0
melanin incontinence                        0
eosinophils in the infiltrate               0
PNL infiltrate                              0
fibrosis of the papillary dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing of the rete ridges                 0
elongation of the rete ridges     

In [32]:
data=data.drop(["Patient ID"],axis=1)
data

Erythema  scaling  definite borders  itching  koebner phenomenon  \
0           2        2                 0        3                   0   
1           3        3                 3        2                   1   
2           2        1                 2        3                   1   
3           2        2                 2        0                   0   
4           2        3                 2        2                   2   
..        ...      ...               ...      ...                 ...   
361         2        1                 1        0                   1   
362         3        2                 1        0                   1   
363         3        2                 2        2                   3   
364         2        1                 3        1                   2   
365         3        2                 2        0                   0   

     polygonal papules  follicular papules  oral mucosal involvement  \
0                    0                   0                         0   
1                    0                   0                         0   
2                    3                   0                         3   
3                    0                   0                         0   
4                    2                   0                         2   
..                 ...                 ...                       ...   
361                  0                   0                         0   
362                  0                   0                         0   
363                  2                   0                         2   
364                  3                   0                         2   
365                  0                   0                         0   

     knee and elbow involvement  scalp involvement  ...  \
0                             1                  0  ...   
1                             1                  1  ...   
2                             0                  0  ...   
3                             3                  2  ...   
4                             0                  0  ...   
..                          ...                ...  ...   
361                           0                  0  ...   
362                           0                  0  ...   
363                           0                  0  ...   
364                           0                  0  ...   
365                           3                  3  ...   

     disappearance of the granular layer  \
0                                      0   
1                                      0   
2                                      0   
3                                      3   
4                                      2   
..                                   ...   
361                                    0   
362                                    1   
363                                    0   
364                                    0   
365                                    2   

     vacuolisation and damage of basal layer  spongiosis  \
0                                          0           3   
1                                          0           0   
2                                          2           3   
3                                          0           0   
4                                          3           2   
..                                       ...         ...   
361                                        0           1   
362                                        0           1   
363                                        3           0   
364                                        2           0   
365                                        0           0   

     saw-tooth appearance of retes  follicular horn plug  \
0                                0                     0   
1                                0                     0   
2                                2                     0   
3                                0                     0   
4   

In [33]:
#finding the unique value
for i in data.columns:
    print(data[i].unique())


[2 3 1 0]
[2 3 1 0]
[0 3 2 1]
[3 2 0 1]
[0 1 2 3]
[0 3 2 1]
[0 3 1 2]
[0 3 2 1]
[1 0 3 2]
[0 1 2 3]
[0 1]
[0 1 2 3]
[0 2 1]
[0 1 3 2]
[0 3 1 2]
[3 1 0 2]
[2 3 1 0]
[0 2 1 3]
[0 2 3 1]
[0 2 1 3]
[0 2 3 1]
[0 2 3 1]
[0 2 1 3]
[0 1 2 3]
[0 2 3 1]
[0 3 2 1]
[0 2 3 1]
[3 0 2 1]
[0 2 3 1]
[0 1 2 3]
[0 2 1 3]
[1 2 3 0]
[0 3 1 2]
['55' '8' '26' '40' '45' '41' '18' '57' '22' '30' '20' '21' '10' '65' '38'
 '23' '17' '51' '42' '44' '33' '43' '50' '34' '?' '15' '46' '62' '35' '48'
 '12' '52' '60' '32' '19' '29' '25' '36' '13' '27' '31' '28' '64' '39'
 '47' '16' '0' '7' '70' '37' '61' '67' '56' '53' '24' '58' '49' '63' '68'
 '9' '75']
[2 1 3 5 4 6]


In [34]:
data[data['Age (linear)']=='?']

Erythema  scaling  definite borders  itching  koebner phenomenon  \
33          2        2                 1        0                   0   
34          2        1                 0        0                   2   
35          2        2                 1        2                   0   
36          2        1                 2        3                   2   
262         2        1                 0        2                   0   
263         1        1                 1        3                   0   
264         1        1                 0        2                   0   
265         1        1                 0        3                   0   

     polygonal papules  follicular papules  oral mucosal involvement  \
33                   0                   0                         0   
34                   0                   0                         0   
35                   0                   0                         0   
36                   3                   0                         2   
262                  0                   0                         0   
263                  0                   0                         0   
264                  0                   0                         0   
265                  0                   0                         0   

     knee and elbow involvement  scalp involvement  ...  \
33                            1                  0  ...   
34                            0                  0  ...   
35                            0                  0  ...   
36                            0                  0  ...   
262                           0                  0  ...   
263                           0                  0  ...   
264                           1                  0  ...   
265                           0                  0  ...   

     disappearance of the granular layer  \
33                                     0   
34                                     0   
35                                     0   
36                                     0   
262                                    0   
263                                    0   
264                                    0   
265                                    0   

     vacuolisation and damage of basal layer  spongiosis  \
33                                         0           0   
34                                         0           0   
35                                         0           0   
36                                         2           0   
262                                        0           2   
263                                        0           3   
264                                        0           2   
265                                        0           2   

     saw-tooth appearance of retes  follicular horn plug  \
33                               0                     0   
34                               0                     0   
35                               0                     0   
36                               2                     0   
262                              0                     0   
263                              0                     0   
264                              0                     0   
265                              0                     0   

     perifollicular parakeratosis  inflammatory monoluclear infiltrate  \
33                              0                                    0   
34                              0                                    0   
35                              0                                    0   
36                              0                                    0   
262                             0                                    3   
263                             0                                    2   
264                             0                                    3   
265                             0                                    3   

     band-like infil

In [ ]:
"""
In the age colume there is a value like " ? " It is problem for train the system it can be give us wrong accuracy for training.
so we need to clean it and fill the value by skweness techique
"""

In [35]:
#data cleaning
import numpy as np
from numpy import NaN
new_data=data.replace("?",NaN)
new_data
new_data['Age (linear)'].unique()

array(['55', '8', '26', '40', '45', '41', '18', '57', '22', '30', '20',
       '21', '10', '65', '38', '23', '17', '51', '42', '44', '33', '43',
       '50', '34', nan, '15', '46', '62', '35', '48', '12', '52', '60',
       '32', '19', '29', '25', '36', '13', '27', '31', '28', '64', '39',
       '47', '16', '0', '7', '70', '37', '61', '67', '56', '53', '24',
       '58', '49', '63', '68', '9', '75'], dtype=object)

In [36]:
new_data['Age (linear)'].isnull().sum()

8

In [37]:
new_data[new_data['Age (linear)'].isnull()]

Erythema  scaling  definite borders  itching  koebner phenomenon  \
33          2        2                 1        0                   0   
34          2        1                 0        0                   2   
35          2        2                 1        2                   0   
36          2        1                 2        3                   2   
262         2        1                 0        2                   0   
263         1        1                 1        3                   0   
264         1        1                 0        2                   0   
265         1        1                 0        3                   0   

     polygonal papules  follicular papules  oral mucosal involvement  \
33                   0                   0                         0   
34                   0                   0                         0   
35                   0                   0                         0   
36                   3                   0                         2   
262                  0                   0                         0   
263                  0                   0                         0   
264                  0                   0                         0   
265                  0                   0                         0   

     knee and elbow involvement  scalp involvement  ...  \
33                            1                  0  ...   
34                            0                  0  ...   
35                            0                  0  ...   
36                            0                  0  ...   
262                           0                  0  ...   
263                           0                  0  ...   
264                           1                  0  ...   
265                           0                  0  ...   

     disappearance of the granular layer  \
33                                     0   
34                                     0   
35                                     0   
36                                     0   
262                                    0   
263                                    0   
264                                    0   
265                                    0   

     vacuolisation and damage of basal layer  spongiosis  \
33                                         0           0   
34                                         0           0   
35                                         0           0   
36                                         2           0   
262                                        0           2   
263                                        0           3   
264                                        0           2   
265                                        0           2   

     saw-tooth appearance of retes  follicular horn plug  \
33                               0                     0   
34                               0                     0   
35                               0                     0   
36                               2                     0   
262                              0                     0   
263                              0                     0   
264                              0                     0   
265                              0                     0   

     perifollicular parakeratosis  inflammatory monoluclear infiltrate  \
33                              0                                    0   
34                              0                                    0   
35                              0                                    0   
36                              0                                    0   
262                             0                                    3   
263                             0                                    2   
264                             0                                    3   
265                             0                                    3   

     band-like infil

In [44]:
new_data['Age (linear)']=new_data['Age (linear)'].astype('Int64')

In [45]:
new_data.dtypes

Erythema                                    int64
scaling                                     int64
definite borders                            int64
itching                                     int64
koebner phenomenon                          int64
polygonal papules                           int64
follicular papules                          int64
oral mucosal involvement                    int64
knee and elbow involvement                  int64
scalp involvement                           int64
family history, (0 or 1)                    int64
melanin incontinence                        int64
eosinophils in the infiltrate               int64
PNL infiltrate                              int64
fibrosis of the papillary dermis            int64
exocytosis                                  int64
acanthosis                                  int64
hyperkeratosis                              int64
parakeratosis                               int64
clubbing of the rete ridges                 int64


In [47]:
new_data['Age (linear)'].fillna(int(new_data['Age (linear)'].mean()),inplace=True)

In [48]:
new_data.dtypes

Erythema                                    int64
scaling                                     int64
definite borders                            int64
itching                                     int64
koebner phenomenon                          int64
polygonal papules                           int64
follicular papules                          int64
oral mucosal involvement                    int64
knee and elbow involvement                  int64
scalp involvement                           int64
family history, (0 or 1)                    int64
melanin incontinence                        int64
eosinophils in the infiltrate               int64
PNL infiltrate                              int64
fibrosis of the papillary dermis            int64
exocytosis                                  int64
acanthosis                                  int64
hyperkeratosis                              int64
parakeratosis                               int64
clubbing of the rete ridges                 int64


In [49]:
new_data.iloc[33]

Erythema                                     2
scaling                                      2
definite borders                             1
itching                                      0
koebner phenomenon                           0
polygonal papules                            0
follicular papules                           0
oral mucosal involvement                     0
knee and elbow involvement                   1
scalp involvement                            0
family history, (0 or 1)                     1
melanin incontinence                         0
eosinophils in the infiltrate                0
PNL infiltrate                               2
fibrosis of the papillary dermis             0
exocytosis                                   0
acanthosis                                   2
hyperkeratosis                               1
parakeratosis                                2
clubbing of the rete ridges                  2
elongation of the rete ridges                1
thinning of t